Домашнее задание №1
made-ml-in-prod-2021/polikutinevgeny pull request #2
Opened 2021-04-29 01:24 UTC by polikutinevgeny

Проект был сгенерирован через cookiecutter, после чего я подчистил лишние папки. Общая структура похожа на пример с занятий.
Код лежит в папке `heart_disease`:

- `data` - считывание данных
- `features` - обработка
- `entities` - dataclassы для конфигов
- `models` - код моделей
- `visualization` - скрипт, генерирующий отчёт с EDA

Тесты в `tests`, структура такая же.

Для конфигов используется hydra. До конца я всё же её не освоил, да и использую всё же я её не в полную силу, но штука интересная, хоть местами и не хватает фич.

Датасет - heart-disease-uci, как и предлагалось в задании.

2021-04-29 01:30 UTC, polikutinevgeny commented
А теперь - самооценка:

-2) Назовите ветку homework1 (1 балл) _+ 1 балл_
-1) положите код в папку ml_project
0) В описании к пулл реквесту описаны основные "архитектурные" и тактические решения, которые сделаны в вашей работе. В общем, описание что именно вы сделали и для чего, чтобы вашим ревьюерам было легче понять ваш код. (2 балла) _+ 2 балла_

1) Выполнение EDA, закоммитьте ноутбук в папку с ноутбуками (2 баллов)
Вы так же можете построить в ноутбуке прототип(если это вписывается в ваш стиль работы)
Можете использовать не ноутбук, а скрипт, который сгенерит отчет, закоммитьте и скрипт и отчет (за это + 1 балл) _+ 3 балла_

2) Проект имеет модульную структуру(не все в одном файле =) ) (2 баллов) _+ 2 балла_

3) использованы логгеры (2 балла) _+ 2 балла_

4) написаны тесты на отдельные модули и на прогон всего пайплайна(3 баллов) _+ 3 балла_

5) Для тестов генерируются синтетические данные, приближенные к реальным (3 баллов) 
- можно посмотреть на библиотеки https://faker.readthedocs.io/en/, https://feature-forge.readthedocs.io/en/latest/
- можно просто руками посоздавать данных, собственноручно написанными функциями
как альтернатива, можно закоммитить файл с подмножеством трейна(это не оценивается) _+ 3 балла_

6) Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла) _+ 3 балла_

7) Используются датаклассы для сущностей из конфига, а не голые dict (3 балла) _+ 3 балла_

8) Используйте кастомный трансформер(написанный своими руками) и протестируйте его(3 балла) _+ 3 балла_

9) Обучите модель, запишите в readme как это предлагается (3 балла) _+ 3 балла_

10) напишите функцию predict, которая примет на вход артефакт/ы от обучения, тестовую выборку(без меток) и запишет предикт, напишите в readme как это сделать (3 балла) _+ 3 балла_

11) Используется hydra  (https://hydra.cc/docs/intro/) (3 балла - доп баллы) _+ 3 балла_

12) Настроен CI(прогон тестов, линтера) на основе github actions  (3 балла - доп баллы (будем проходить дальше в курсе, но если есть желание поразбираться - welcome) _+ 0 баллов_
13) Проведите самооценку, опишите, в какое колво баллов по вашему мнению стоит оценить вашу работу и почему (1 балл доп баллы) _+ 1 балл (рекурсия)_

Итого: 35 баллов :)

2021-05-04 13:00 UTC, Mikhail-M requested changes
Выглядит хорошо, спасибо за работу!

Баллы: 35

Как дополнительное улучшение можно еще посмотреть на scope и прописать их в тестах
https://habr.com/ru/post/448786/

2021-05-04 13:01 UTC, Mikhail-M approved these changes
Выглядит хорошо, спасибо за работу!

Баллы: 35

Как дополнительное улучшение можно еще посмотреть на scope и прописать их в тестах
https://habr.com/ru/post/448786/

2021-05-07 07:07 UTC, RonWise approved these changes
Отличная работа 👍

2021-05-08 07:14 UTC, merged